name: Murder
author: TheNewHEROBRINE
version: 0.8
api: ["3.0.0-ALPHA7"]
main: TheNewHEROBRINE\Murder\MurderMain

permissions:
 murder:
  children:
   murder.command:
    children:
     murder.command.join:
      default: true
     murder.command.quit:
      default: true
     murder.command.setarena:
      default: op