name: Murder
authors: TheNewHEROBRINE
version: 0.8
api: ["2.1.0", "2.0.0", "3.0.0-ALPHA1", "3.0.0-ALPHA2", "3.0.0"]
main: TheNewHEROBRINE\Murder\MurderMain

permissions:
 murder:
  children:
   murder.command:
    children:
     murder.command.join:
      default: true
     murder.command.quit:
      default: true
     murder.command.setspawns:
      default: true
